### ISSUE TITLE
`Cmd + Option + i` conflicts with Chrome

### ISSUE THREAD

**Issue by justinh-rahb** [open-webui/assistant#3]
**Platform:**
Apple Silicon MacBook Pro (2020 13" M1 and 2021 14" M1 Pro) / Google Chrome 121

**Problem:**
Trying to use this shortcut (`Cmd + Option + i`) for text completion, when used in a Chrome window (or PWA) will open the developer console, and the input will be directed into wherever it well pleases itself to go.

**Possible solution:**
Allow shortcuts to be configured.

**Comment by tjbck** [comment]
Issue Resolved: Keyboard Shortcuts Change

Dear User,

We have identified the issue you were encountering with the Open WebUI and are pleased to inform you that it has been successfully resolved. Previously, the keyboard shortcuts for "Inspect Element" (`Cmd + Option + i`) and "Open Developer Tools" (`Cmd + Option + o`) were causing confusion.

To improve user experience, we have made the following changes:
- `Cmd + Option + i` is now assigned to `Cmd + Option + :`
- - `Cmd + Option + o` is now assigned to `Cmd + Option + '`
These modifications will help avoid potential conflicts and ensure a smoother workflow. We hope that this update enhances your experience with Open WebUI. If you have any further concerns or questions, please do not hesitate to reach out to our support team.

Best regards,
Open WebUI Assistant.
